-- ============================================================
-- 0036 - Remitos, prestamos y presupuestos
-- ============================================================

create table if not exists public.delivery_notes (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  issued_at date not null default current_date,
  created_by uuid references public.profiles(id) on delete set null,
  created_by_name text,
  type text not null check (type in ('delivery', 'loan', 'quote')),
  status text not null default 'issued' check (status in ('issued', 'returned', 'cancelled')),
  customer_name text not null,
  customer_contact text,
  customer_address text,
  loan_due_at date,
  returned_at timestamptz,
  notes text
);

create table if not exists public.delivery_note_items (
  id uuid primary key default gen_random_uuid(),
  delivery_note_id uuid not null references public.delivery_notes(id) on delete cascade,
  created_at timestamptz not null default now(),
  product_id uuid references public.products(id) on delete set null,
  variant_gid text,
  inventory_item_id text,
  article text not null,
  color text,
  talle text,
  qty integer not null default 1 check (qty > 0),
  unit_price numeric not null default 0 check (unit_price >= 0),
  discount numeric not null default 0 check (discount >= 0 and discount < 1),
  stock_deducted boolean not null default false
);

create index if not exists idx_delivery_notes_issued
  on public.delivery_notes (issued_at desc, number desc);
create index if not exists idx_delivery_notes_type_status
  on public.delivery_notes (type, status, issued_at desc);
create index if not exists idx_delivery_note_items_note
  on public.delivery_note_items (delivery_note_id);

alter table public.delivery_notes enable row level security;
alter table public.delivery_note_items enable row level security;

drop policy if exists "delivery_notes_staff_select" on public.delivery_notes;
create policy "delivery_notes_staff_select" on public.delivery_notes
  for select to authenticated
  using (
    exists (select 1 from public.profiles p
            where p.id = (select auth.uid()) and p.role in ('admin', 'vendedor'))
  );

drop policy if exists "delivery_notes_staff_insert" on public.delivery_notes;
create policy "delivery_notes_staff_insert" on public.delivery_notes
  for insert to authenticated
  with check (
    exists (select 1 from public.profiles p
            where p.id = (select auth.uid()) and p.role in ('admin', 'vendedor'))
  );

drop policy if exists "delivery_notes_staff_update" on public.delivery_notes;
create policy "delivery_notes_staff_update" on public.delivery_notes
  for update to authenticated
  using (
    exists (select 1 from public.profiles p
            where p.id = (select auth.uid()) and p.role in ('admin', 'vendedor'))
  )
  with check (
    exists (select 1 from public.profiles p
            where p.id = (select auth.uid()) and p.role in ('admin', 'vendedor'))
  );

drop policy if exists "delivery_notes_staff_delete" on public.delivery_notes;
create policy "delivery_notes_staff_delete" on public.delivery_notes
  for delete to authenticated
  using (
    exists (select 1 from public.profiles p
            where p.id = (select auth.uid()) and p.role in ('admin', 'vendedor'))
  );

drop policy if exists "delivery_note_items_staff_select" on public.delivery_note_items;
create policy "delivery_note_items_staff_select" on public.delivery_note_items
  for select to authenticated
  using (
    exists (select 1 from public.profiles p
            where p.id = (select auth.uid()) and p.role in ('admin', 'vendedor'))
  );

drop policy if exists "delivery_note_items_staff_insert" on public.delivery_note_items;
create policy "delivery_note_items_staff_insert" on public.delivery_note_items
  for insert to authenticated
  with check (
    exists (select 1 from public.profiles p
            where p.id = (select auth.uid()) and p.role in ('admin', 'vendedor'))
  );

drop policy if exists "delivery_note_items_staff_update" on public.delivery_note_items;
create policy "delivery_note_items_staff_update" on public.delivery_note_items
  for update to authenticated
  using (
    exists (select 1 from public.profiles p
            where p.id = (select auth.uid()) and p.role in ('admin', 'vendedor'))
  )
  with check (
    exists (select 1 from public.profiles p
            where p.id = (select auth.uid()) and p.role in ('admin', 'vendedor'))
  );

drop policy if exists "delivery_note_items_staff_delete" on public.delivery_note_items;
create policy "delivery_note_items_staff_delete" on public.delivery_note_items
  for delete to authenticated
  using (
    exists (select 1 from public.profiles p
            where p.id = (select auth.uid()) and p.role in ('admin', 'vendedor'))
  );

comment on table public.delivery_notes is
  'Documentos imprimibles: remitos de entrega, prestamos y presupuestos.';
comment on column public.delivery_note_items.stock_deducted is
  'Solo se usa en prestamos: indica que Atelier desconto la unidad y debe reponerla al devolver o cancelar.';

